config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/navbar'
  get 'static_pages/footer'
  get 'static_pages/forms'
  get 'static_pages/banners'
  get 'static_pages/cards'
  get 'static_pages/comments'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def navbar
  end

  def footer
  end

  def forms
  end

  def banners
  end

  def cards
  end

  def comments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Molecules</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
      <div class="container">
        <a href="<%= root_path %>" class="navbar-brand">Bootswatch</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Components <span class="caret"></span></a>
              <div class="dropdown-menu" aria-labelledby="download">
                <a class="dropdown-item" href="<%= static_pages_navbar_path %>">Navbar</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"href="<%= static_pages_footer_path %>">Footer</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<%= static_pages_forms_path %>">Forms</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<%= static_pages_banners_path %>">Banners</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<%= static_pages_cards_path %>">Cards</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<%= static_pages_comments_path %>">Comments</a>
                <div class="dropdown-divider"></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/static_pages/banners.html.erb
<!-- Banner Md -->
<h1 class="text-center">Banner Md</h1>
<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <h1 class="display-4">Title Md</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis consequatur consequuntur culpa debitis eius error libero minima nam necessitatibus nemo nisi officia, provident quis recusandae repellendus vitae voluptatum. Animi, deleniti.</p>
  </div>
  <a class="btn btn-primary btn-md" href="#" role="button">CTA</a>
</div>
<!-- end -->

<!-- Banner Lg -->
<h1 class="text-center">Banner Lg</h1>
<div class="jumbotron jumbotron-fluid text-center">
  <h1 class="display-3">Title Lg</h1>
  <div class="container">
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis consequatur consequuntur culpa debitis eius error libero minima nam necessitatibus nemo nisi officia, provident quis recusandae repellendus vitae voluptatum. Animi, deleniti.</p>
  </div>
  <a class="btn btn-primary btn-lg" href="#" role="button">CTA</a>
</div>
<!-- end  -->

app/views/static_pages/cards.html.erb
<h1 class="text-center">Event's index</h1>

<!-- Cards index -->
<div class="container d-flex justify-content-center mt-3">
  <div class="card mb-4 box-shadow box-shadow-hover border-primary">
    <div class="card-header">
      <p>"Title"</p>
    </div>
    <div class="card-body">
      <p class="card-text">Description</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "See more", "#", class:"btn btn-sm btn-outline-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end -->

<h1 class="text-center mt-3">Cities index</h1>

<!-- City card -->
<div class="container d-flex justify-content-center mt-3">
  <div class="card w-50">
    <div class="card-body">
      <h5 class="card-title">City name</h5>
      <p class="card-text">#number of events</p>
      <a href="#" class="btn btn-outline-primary">See events</a>
    </div>
  </div>
</div>
<!-- end -->

<h1 class="text-center mt-3">Cards index</h1>

<!-- Cards show -->
<div class="album py-5">
  <div class="container">
    <div class="card-columns">
      <% 6.times do %>
        <div class="card mb-4 box-shadow box-shadow-hover border-primary">
          <div class="card-body">
            <p class="card-text"><%= "Title " %></p>
            <p class="card-text"><%= "Description and more " %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= link_to "See more", "#", class:"btn btn-sm btn-outline-primary" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- end -->
<h1 class="text-center mt-3">Event users</h1>

<!-- Event user show -->
<div class="container">
  <div class="my-3 p-3 bg-shadow rounded box-shadow">
    <h6 class="border-bottom border-gray pb-2 mb-0">Users</h6>
    <div class="container d-flex justify-content-center mt-3">
      <div class="media text-muted pt-3 w-100">
        <img src="https://via.placeholder.com/50" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><a href="#">User Name</a></strong>
          Description / city
        </p>
      </div>
    </div>
    <div class="container d-flex justify-content-center mt-3">
      <div class="media text-muted pt-3 w-100">
        <img src="https://via.placeholder.com/50" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><a href="#">User Name</a></strong>
          Description / city
        </p>
      </div>
    </div>
    <div class="container d-flex justify-content-center mt-3">
      <div class="media text-muted pt-3 w-100">
        <img src="https://via.placeholder.com/50" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><a href="#">User Name</a></strong>
          Description / city
        </p>
      </div>
    </div>
    <small class="d-block text-right mt-3">
      <a href="#">All users</a>
    </small>
  </div>
</div>
<!-- end -->

<h1 class="text-center mt-3">Users cards</h1>

<!-- User index -->
<div class="container d-flex justify-content-center mt-3">
  <div class="media text-muted pt-3 w-50">
    <img src="https://via.placeholder.com/50" alt="" class="mr-2 rounded">
    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
      <strong class="d-block text-gray-dark"><a href="#">User Name</a></strong>
      Description / city
    </p>
  </div>
</div>
<!-- end -->

app/views/static_pages/comments.html.erb
<!-- Comment index start -->
<h1 class="text-center mt-3">Comments area</h1>
<div class="container">
  <div class="my-3 p-3 bg-light rounded box-shadow">
    <h6 class="border-bottom border-gray pb-2 mb-0">Comments</h6>
    <% 3.times do %>
      <div class="media text-muted pt-3 w-100">
        <img src="https://via.placeholder.com/50" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><a href="#">@user_name</a></strong>
          Comment
        </p>
        <p class="text-muted align-self-center"><small>Location</small></p>
      </div>
    <% end %>
    <small class="d-block text-right mt-3">
      <a href="#">All Comments</a>
    </small>
    <form class="form mt-3">
      <div class="form-group">
        <textarea class="form-control" placeholder="Your comment..."></textarea>
      </div>
      <button type="submit" class="btn btn-primary btn-block">
        Comment
      </button>
    </form>
  </div>
</div>
<!-- Comment index end -->

<!-- Comment card start -->
<h1 class="text-center mt-3">Comments</h1>
<div class="container d-flex justify-content-center mt-3">
  <div class="media text-muted pt-3 w-100">
    <img src="https://via.placeholder.com/50" alt="" class="mr-2 rounded">
    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
      <strong class="d-block text-gray"><a href="#">@user_name</a></strong>
      Comment
    </p>
    <p class="text-muted align-self-center"><small>Location</small></p>
  </div>
</div>
<!-- Comment card end -->

app/views/static_pages/footer.html.erb
<h1 class="text-center">Footer</h1>

<!-- Footer -->
<footer class="bg-primary">
  <div class="text-center py-3 text-light">© 2064 Copyright:
    <a href="<%= root_path %>" class="text-light"> mywebsite.com</a>
    <a href="#!" class="text-light m-3">Contact</a>
    <a href="#!" class="text-light">Social networks</a>
  </div>
</footer>
<!-- end -->

app/views/static_pages/forms.html.erb
<!-- Log in form -->
<div class="container mt-10rem">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class="text-center">Forms</h2>
      <form>
        <div class="form-group">
          <%= label_tag :email %><br />
          <%= email_field_tag :email, "", autofocus: true, autocomplete: "email", class:"form-control" %>
        </div>

        <div class="form-group">
          <%= label_tag :password %><br />
          <%= password_field_tag :password, "", autocomplete: "current-password", class:"form-control" %>
        </div>

        <div class="btn-group btn-group-toggle form-group" data-toggle="buttons">
          <label class="btn btn-outline-primary">
            <input type="checkbox" autocomplete="off"> Remember me
          </label>
        </div>
        <div class="actions mt-5">
          <%= submit_tag "Connect", class:"btn btn-primary btn-block"  %>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- end -->

app/views/static_pages/navbar.html.erb
<!-- Navbar start -->
<div class="container mt-5">
  <h1 class="text-center">Navbar</h1>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="height: 4rem">
    <a class="navbar-brand" href="#">BRITEVENT</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse bg-primary navbar-dark" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item ">
          <a class="nav-link" href="#">Home <span class="sr-only"</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Create Event <span class="sr-only"></span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sign up / Sign in
          </a>
          <div class="dropdown-menu bg-primary " aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item text-white" href="#">Sign up</a>
            <a class="dropdown-item text-white" href="#">Sign in</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle " href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My profile
            </a>
          <div class="dropdown-menu bg-primary" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item text-white" href="#">My profile</a>
              <%= link_to "Disconnect", '#', method: :delete, class:"dropdown-item text-white"%>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</div>
<!-- Navbar end -->